%   USAGE:   gs_response
% 
%   PURPOSE: Calculate how the plasma responds to the independent variables (x)
%            The independent variables are:
%            conductor currents ic; iv
%            profile spline parameters: sp; sf
%            fraction remaining flux error: er
% 
%   INPUTS: several variables generated by gs_eq_analysis are needed
% 
%   OUTPUTS: Responses of several quantities d*dx
% 	
%   METHOD: 
%